spring:
  application:
    name: firstProject
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
# 데이터 베이스 설정
  datasource:
    generate-unique-name: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/testDB?serverTimezone'
    username: testUser
    password: '1234'
  thymeleaf:
    cache: false

server:
  servlet:
    encoding:
      force: true
#logging관련 설정
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
